### ISSUE TITLE
Remove EDP Component Permission from Tekton Role

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-tekton#113]
We currently have a permission in the `tekton-role` that allows it to retrieve `edpcomponents` from the `v1.edp.epam.com` API:

```yaml
- apiGroups:
    - 'v1.edp.epam.com'
  resources:
    - edpcomponents
  verbs:
    - get
```

This ticket aims to remove this permission as it's no longer needed. The role shouldn't have access to EDP components as the URL for the Docker registry is now retrieved differently.

This change will help us maintain the principle of least privilege and ensure our Tekton role only has the permissions it needs.

**Acceptance Criteria:**

1. The permission to get `edpcomponents` from `v1.edp.epam.com` is removed from `tekton-role`.
