### ISSUE TITLE
Create cdxgen Task

### ISSUE THREAD

**Issue by SergK** [epam/edp-tekton#16]
Create cdxgen Task and add it to the EDP4EDP Pipelines (in SCA step)

Here is a code that works:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Dep-Analysis
    tekton.dev/platforms: linux/amd64
  name: cdxgen
spec:
  params:
    - default: ''
      description: Dependency Track URL which is used for pushing SBOM
      name: DEPTRACK_URL
      type: string
  steps:
    - env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: ci-dependency-track
        - name: DEPTRACK_URL
          value: $(params.DEPTRACK_URL)
      image: >-
        ghcr.io/cyclonedx/cdxgen:v9.6.0@sha256:ea01324872d2c21b024264a2224d761ab63851b9cc4722903b5e74be56ca6fa6
      name: cdxgen
      resources: {}
      script: >
        #!/usr/bin/env sh
        set -e
        set +x
        /opt/cdxgen/bin/cdxgen.js --api-key=$API_TOKEN --server-url=$DEPTRACK_URL --project-name=CODEBASENAME
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
```
