### ISSUE TITLE
[refactoring] CD Pipeline deployment

### ISSUE THREAD

**Issue by SergK** [epam/edp-tekton#96]
**Is your feature request related to a problem? Please describe.**
The current deployment process lacks proper synchronization and health check features, leading to potential inconsistencies and deployment issues in the target environment.

**Describe the solution you'd like**
Introduce synchronization and health check steps in the deployment process to ensure the consistency and health of deployed applications. Add the Tekton Pipeline `cd-stage-deploy` to include these new steps.

**Describe alternatives you've considered**
At present, the deployment process is dependent on the number of pipelines and tasks, which contain a lot of complex logic. This results in difficulties in providing support. 

**Additional context**
The following modifications should be made to the `cd-stage-deploy` Tekton Pipeline:

1. Introduce a new task, let's call it `check-sync`, responsible for checking synchronization status and health of the deployed applications in ArgoCD.

2. Update the `cd-stage-deploy` Pipeline to include the new `check-sync` task after the `deploy-app` task.

The new task `check-sync` can be based on the following specifications:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-sync
spec:
  description: |
    This task is responsible for checking synchronization status and health of the deployed applications in ArgoCD.

  params:
    - name: STAGE
      description: |
        EDP kind:Stage name of the kind:CDPipeline defined in the CDPIPELINE values. For example: dev, test, prod
      type: string

  steps:
    - name: wait-for-argocd-sync
      image: sergk/edp-argocd-cli:0.2.0-dev
      env:
        - name: ARGOCD_SERVER
          valueFrom:
            secretKeyRef:
              name: ci-argocd
              key: url
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ci-argocd
              key: token
      script: |
        set -ex

        selector="app.edp.epam.com/stage=$(params.STAGE)"

        argocd app wait -l $selector --health --sync
```

And the modified `cd-stage-deploy` Pipeline:

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-stage-deploy
  labels:
    app.edp.epam.com/pipeline: general-deployment
    app.edp.epam.com/pipelinetype: deploy
spec:
  description: |
    This Pipeline is used to deploy applications to the target Stage (Environment).
  params:
    # ... (existing parameters)

  tasks:
    - name: pre-deploy
      # ... (existing task)

    - name: deploy-app
      # ... (existing task)

    - name: check-sync
      taskRef:
        kind: Task
        name: check-sync
      runAfter:
        - deploy-app
      params:
        - name: STAGE
          value: $(params.CDSTAGE)

    - name: post-deploy
      # ... (existing task)
```

These changes will enhance the deployment process by ensuring synchronization and health checks are performed after the deployment of applications in the target environment.
